### ISSUE TITLE
Unknown Type: 46

### ISSUE THREAD

**Issue by josephw** [josephw/titl#6]
Original [issue 6](https://code.google.com/p/titl/issues/detail?id=6) created by josephw on 2010-05-01T18:50:49.000Z:

Try to parse the attached iTunes Library (Mine)

I get unknown type 46, I think I'm running everything else correctly.

**Comment by Riddeck07** [comment]
> Comment [#1](https://code.google.com/p/titl/issues/detail?id=6#c1) originally posted by josephw on 2010-09-29T15:12:29.000Z:
> 
> Type 46 appears to be a copyright notice. I've added it to the list of recognised types. Thanks

in case of all pc "types with digits"? i mean, same thing in dos -- nslookup.exe query?
[unknown type nslookup.txt](https://github.com/josephw/titl/files/3195137/unknown.type.nslookup.txt)
